# DataVines Plugin Descriptor
plugin.name=last_30d_avg
plugin.module=expected-value
plugin.version=1.0.0-SNAPSHOT
plugin.spi.version=1.0.0
plugin.main.version.range=[1.0.0,2.0.0)
plugin.description=datavines-metric-expected-last30day-avg (ExpectedValue)
