# DataVines Plugin Descriptor
plugin.name=multi_table_value_comparison
plugin.version=1.0.0-SNAPSHOT
plugin.spi.version=1.0.0
plugin.main.version.range=[1.0.0,2.0.0)
plugin.description=datavines-metric-multi-table-value-comparison (SqlMetric)
