# DataVines Plugin Descriptor
plugin.name=postgresql
plugin.module=connector
plugin.version=1.0.0-SNAPSHOT
plugin.spi.version=1.0.0
plugin.main.version.range=[1.0.0,2.0.0)
plugin.description=datavines-connector-postgresql (ConnectorFactory)
