# DataVines Plugin Descriptor
plugin.name=zookeeper
plugin.module=registry
plugin.version=1.0.0-SNAPSHOT
plugin.spi.version=1.0.0
plugin.main.version.range=[1.0.0,2.0.0)
plugin.description=datavines-registry-zookeeper (Registry)
