# DataVines Plugin Descriptor
plugin.name=starrocks
plugin.module=connector
plugin.version=1.0.0-SNAPSHOT
plugin.spi.version=1.0.0
plugin.main.version.range=[1.0.0,2.0.0)
plugin.description=datavines-connector-starrocks (ConnectorFactory)
plugin.dependencies=com.mysql:mysql-connector-j
