# DataVines Plugin Descriptor
plugin.name=flink-config
plugin.module=engine
plugin.version=1.0.0-SNAPSHOT
plugin.spi.version=1.0.0
plugin.main.version.range=[1.0.0,2.0.0)
plugin.description=datavines-engine-flink-config (JobConfigurationBuilder)
